#!/usr/bin/env python3
"""logs-to-cookie (single-file edition).

Sort and convert stealer-style log dumps into ULP and cookie formats.

No install needed — just::

    python logs_to_cookie.py --help
    python logs_to_cookie.py ulp     /path/to/logs -o creds.txt
    python logs_to_cookie.py cookies /path/to/logs -o cookies.txt
    python logs_to_cookie.py sort    /path/to/logs --keywords netflix,spotify -o sorted/

Stdlib only, Python 3.9+.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path
from typing import Callable, Dict, Iterable, Iterator, List, Optional, Tuple

__version__ = "0.10.0"


# Re-exposed so old code that did `from urllib.parse import urlparse` keeps
# working when copy-pasted from this single file.
urlparse = urllib.parse.urlparse

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

PASSWORD_NAME_HINTS = (
    "password",
    "passwords",
    "all passwords",
    "all_passwords",
    "passwordsall",
    "logins",
    "credentials",
)

URL_RE = re.compile(
    r"^(?:URL|HOST(?:NAME)?|SITE|SOFT\s*URL|ORIGIN|URL\s*\(form\)|URL\s*Origin)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
USER_RE = re.compile(
    r"^(?:USER(?:NAME)?|LOGIN|EMAIL|USER\s*ID|USER\s*NAME)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
PASS_RE = re.compile(
    r"^(?:PASS(?:WORD)?|PWD)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
INLINE_ULP_RE = re.compile(
    r"^(?P<url>(?:https?|android)://[^/:\s]+(?::\d+)?(?:/[^\s:]*)?):"
    r"(?P<user>[^:\s]+):"
    r"(?P<pwd>.+)$"
)

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by logs-to-cookie. Do not edit.\n\n"
)


def domain_of(url: str) -> str:
    try:
        host = urlparse(url).hostname or ""
    except ValueError:
        host = ""
    return host.lower()


# ---------------------------------------------------------------------------
# Credentials parsing
# ---------------------------------------------------------------------------


def _emit(cur: dict) -> Iterator[Tuple[str, str, str]]:
    if cur.get("url") and cur.get("user") is not None and cur.get("pwd") is not None:
        yield cur["url"], cur["user"], cur["pwd"]


def parse_credentials_text(text: str) -> Iterator[Tuple[str, str, str]]:
    """Yield ``(url, user, pwd)`` triples parsed from a credential dump."""
    cur: dict = {"url": None, "user": None, "pwd": None}

    for raw in text.splitlines():
        line = raw.strip().lstrip("\ufeff")
        if not line:
            yield from _emit(cur)
            cur = {"url": None, "user": None, "pwd": None}
            continue

        m = INLINE_ULP_RE.match(line)
        if m:
            yield m.group("url"), m.group("user"), m.group("pwd")
            cur = {"url": None, "user": None, "pwd": None}
            continue

        m = URL_RE.match(line)
        if m:
            yield from _emit(cur)
            cur = {"url": m.group(1).strip(), "user": None, "pwd": None}
            continue
        m = USER_RE.match(line)
        if m:
            cur["user"] = m.group(1).strip()
            continue
        m = PASS_RE.match(line)
        if m:
            cur["pwd"] = m.group(1).strip()
            if cur["url"] and cur["user"] is not None:
                yield cur["url"], cur["user"], cur["pwd"]
                cur = {"url": None, "user": None, "pwd": None}
            continue

    yield from _emit(cur)


def is_password_file(path: Path) -> bool:
    name = path.name.lower()
    if not name.endswith((".txt", ".log")):
        return False
    return any(hint in name for hint in PASSWORD_NAME_HINTS)


def iter_password_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        if is_password_file(root):
            yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and is_password_file(path):
            yield path


def collect_credentials(root: Path) -> Iterator[Tuple[str, str, str, Path]]:
    for path in iter_password_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for url, user, pwd in parse_credentials_text(text):
            yield url, user, pwd, path


# ---------------------------------------------------------------------------
# Cookie parsing / serialization
# ---------------------------------------------------------------------------


def parse_netscape(text: str) -> Iterator[Dict]:
    for raw in text.splitlines():
        if not raw.strip():
            continue
        line = raw
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
        elif line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, flag, path, secure, expires, name, value = parts
        try:
            exp_int = int(float(expires))
        except (TypeError, ValueError):
            exp_int = 0
        yield {
            "domain": domain,
            "hostOnly": flag.strip().upper() != "TRUE",
            "path": path or "/",
            "secure": secure.strip().upper() == "TRUE",
            "expires": exp_int,
            "name": name,
            "value": value,
        }


def parse_json_cookies(text: str) -> Iterator[Dict]:
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if isinstance(data, dict):
        if isinstance(data.get("cookies"), list):
            data = data["cookies"]
        else:
            data = [data]
    if not isinstance(data, list):
        return
    for entry in data:
        if not isinstance(entry, dict):
            continue
        domain = entry.get("domain") or entry.get("Domain") or entry.get("host") or ""
        if not domain:
            continue
        host_only = entry.get("hostOnly")
        if host_only is None:
            host_only = not str(domain).startswith(".")
        expires_raw = (
            entry.get("expirationDate")
            or entry.get("expires")
            or entry.get("Expires")
            or 0
        )
        try:
            expires = int(float(expires_raw))
        except (TypeError, ValueError):
            expires = 0
        yield {
            "domain": str(domain),
            "hostOnly": bool(host_only),
            "path": entry.get("path") or "/",
            "secure": bool(entry.get("secure", False)),
            "expires": expires,
            "name": entry.get("name", ""),
            "value": entry.get("value", ""),
        }


def to_netscape_line(cookie: Dict) -> str:
    domain = cookie.get("domain", "") or ""
    host_only = bool(cookie.get("hostOnly"))
    if host_only:
        if domain.startswith("."):
            domain = domain[1:]
        flag = "FALSE"
    else:
        if domain and not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
    return "\t".join(
        [
            domain,
            flag,
            cookie.get("path") or "/",
            "TRUE" if cookie.get("secure") else "FALSE",
            str(int(cookie.get("expires") or 0)),
            cookie.get("name", "") or "",
            cookie.get("value", "") or "",
        ]
    )


def _looks_like_cookie_path(path: Path) -> bool:
    name = path.name.lower()
    if name.endswith((".txt", ".json")) and "cookie" in name:
        return True
    parents = {p.name.lower() for p in path.parents}
    if "cookies" in parents and path.suffix.lower() in {".txt", ".json", ""}:
        return True
    return False


def iter_cookie_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        if _looks_like_cookie_path(root):
            yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and _looks_like_cookie_path(path):
            yield path


def collect_cookies(root: Path) -> Iterator[Dict]:
    for cookie, _src in collect_cookies_with_source(root):
        yield cookie


def collect_cookies_with_source(root: Path) -> Iterator[Tuple[Dict, Path]]:
    """Like :func:`collect_cookies` but also yields the originating file."""
    for path in iter_cookie_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.strip():
            continue
        stripped = text.lstrip()
        if path.suffix.lower() == ".json" or stripped.startswith(("[", "{")):
            yielded = False
            for cookie in parse_json_cookies(text):
                yielded = True
                yield cookie, path
            if yielded:
                continue
        for cookie in parse_netscape(text):
            yield cookie, path


_ARCHIVE_TEMPDIR_RE = re.compile(r"^x\d{3}_")


def source_name_for(path: Path, root: Path) -> str:
    """Derive a human-friendly source (victim) name for ``path`` under ``root``."""
    try:
        rel = path.resolve().relative_to(root.resolve())
    except ValueError:
        name = path.parent.name or "unknown"
        return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"

    parts = rel.parts
    if parts and parts[0].lower() in ("cookies", "cookie"):
        name = root.name or "unknown"
    elif parts:
        name = parts[0]
    else:
        name = root.name or "unknown"
    return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"


def safe_source_name(name: str) -> str:
    cleaned = "".join(
        c if c.isalnum() or c in "-_.[]()" else "_" for c in (name or "").strip()
    )
    return cleaned or "unknown"


def dedupe_cookies(cookies: Iterable[Dict]) -> List[Dict]:
    seen = set()
    out: List[Dict] = []
    for c in cookies:
        key = (c.get("domain", ""), c.get("path", ""), c.get("name", ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(c)
    return out


# ---------------------------------------------------------------------------
# Archive extraction (password-protected logs)
# ---------------------------------------------------------------------------

ARCHIVE_EXTS = {".zip", ".rar", ".7z"}


def is_archive(path: Path) -> bool:
    return path.suffix.lower() in ARCHIVE_EXTS


def _have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def _seven_zip_binary() -> Optional[str]:
    for cand in ("7z", "7za", "7zz"):
        if _have(cand):
            return cand
    return None


def _try_zip(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    try:
        zf = zipfile.ZipFile(archive)
    except (zipfile.BadZipFile, OSError):
        return False
    try:
        for pwd in passwords:
            pwd_b = pwd.encode("utf-8") if pwd else None
            try:
                zf.extractall(dest, pwd=pwd_b)
                return True
            except RuntimeError:
                continue
            except zipfile.BadZipFile:
                return False
    finally:
        zf.close()
    return False


def _try_7z(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    binary = _seven_zip_binary()
    if not binary:
        return False
    for pwd in passwords:
        cmd = [binary, "x", "-y", f"-o{dest}"]
        cmd.append(f"-p{pwd}" if pwd is not None else "-p")
        cmd.append(str(archive))
        try:
            result = subprocess.run(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=600,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0:
            return True
    return False


def _try_unrar(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    if not _have("unrar"):
        return False
    for pwd in passwords:
        cmd = ["unrar", "x", "-y", "-inul"]
        cmd.append(f"-p{pwd}" if pwd is not None else "-p-")
        cmd.append(str(archive))
        cmd.append(str(dest) + os.sep)
        try:
            result = subprocess.run(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=600,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0:
            return True
    return False


def extract_archive(
    archive: Path, dest: Path, passwords: List[Optional[str]]
) -> bool:
    dest.mkdir(parents=True, exist_ok=True)
    ext = archive.suffix.lower()
    if ext == ".zip":
        if _try_zip(archive, dest, passwords):
            return True
        return _try_7z(archive, dest, passwords)
    if ext == ".rar":
        if _try_unrar(archive, dest, passwords):
            return True
        return _try_7z(archive, dest, passwords)
    if ext == ".7z":
        return _try_7z(archive, dest, passwords)
    return False


def expand_input(
    inputs: Iterable[Path],
    passwords: Iterable[str],
    workdir: Path,
    recurse: bool = True,
) -> Tuple[List[Path], List[Path]]:
    pwd_list: List[Optional[str]] = [None]
    for p in passwords:
        if p and p not in pwd_list:
            pwd_list.append(p)
    workdir.mkdir(parents=True, exist_ok=True)

    roots: List[Path] = []
    failures: List[Path] = []
    queue: List[Path] = []
    seen: set = set()

    for inp in inputs:
        inp = inp.resolve()
        if inp.is_file() and is_archive(inp):
            queue.append(inp)
        else:
            roots.append(inp)

    counter = 0
    while queue:
        archive = queue.pop()
        if archive in seen:
            continue
        seen.add(archive)
        counter += 1
        safe = "".join(c if c.isalnum() or c in "-_." else "_" for c in archive.stem)
        target = workdir / f"x{counter:03d}_{safe or 'arch'}"
        if extract_archive(archive, target, pwd_list):
            roots.append(target)
            if recurse:
                for nested in target.rglob("*"):
                    if nested.is_file() and is_archive(nested) and nested not in seen:
                        queue.append(nested)
        else:
            failures.append(archive)

    return roots, failures


# ---------------------------------------------------------------------------
# Sorter
# ---------------------------------------------------------------------------


def _safe_keyword(k: str) -> str:
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in k.strip()) or "kw"


def sort_logs(
    root, out_dir: Path, keywords: Iterable[str]
) -> Dict[str, Tuple[int, int]]:
    if isinstance(root, Path):
        roots = [root]
    else:
        roots = list(root)
    kws = [k.strip() for k in keywords if k and k.strip()]
    if not kws:
        return {}
    out_dir.mkdir(parents=True, exist_ok=True)

    ulp_handles: Dict[str, "object"] = {}
    cookie_handles: Dict[str, "object"] = {}
    seen_ulp = {k: set() for k in kws}
    seen_cookie = {k: set() for k in kws}
    counts = {k: [0, 0] for k in kws}

    try:
        for k in kws:
            slug = _safe_keyword(k)
            ulp_handles[k] = open(out_dir / f"{slug}.ulp.txt", "w", encoding="utf-8")
            cookie_handles[k] = open(
                out_dir / f"{slug}.cookies.txt", "w", encoding="utf-8"
            )
            cookie_handles[k].write(NETSCAPE_HEADER)

        for r in roots:
            for url, user, pwd, _ in collect_credentials(r):
                host = domain_of(url)
                haystack = (url + " " + host).lower()
                line = f"{url}:{user}:{pwd}"
                for k in kws:
                    if k.lower() in haystack:
                        if line in seen_ulp[k]:
                            continue
                        seen_ulp[k].add(line)
                        ulp_handles[k].write(line + "\n")
                        counts[k][0] += 1

        for r in roots:
            for cookie in collect_cookies(r):
                domain = (cookie.get("domain") or "").lower()
                if not domain:
                    continue
                line = to_netscape_line(cookie)
                for k in kws:
                    if k.lower() in domain:
                        if line in seen_cookie[k]:
                            continue
                        seen_cookie[k].add(line)
                        cookie_handles[k].write(line + "\n")
                        counts[k][1] += 1
    finally:
        for f in ulp_handles.values():
            f.close()
        for f in cookie_handles.values():
            f.close()

    return {k: (counts[k][0], counts[k][1]) for k in kws}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _open_out(path: str):
    if path == "-":
        return sys.stdout, False
    p = Path(path)
    if p.parent and str(p.parent) not in ("", "."):
        p.parent.mkdir(parents=True, exist_ok=True)
    return open(p, "w", encoding="utf-8"), True


# ---------------------------------------------------------------------------
# HTTP stream downloader (range-split parallel + single-stream fallback)
# ---------------------------------------------------------------------------

_DL_CHUNK = 1024 * 1024
# Per-read socket timeout. urllib raises socket.timeout if no bytes
# arrive in this many seconds, which the part loop catches as a retry
# trigger. Tight enough to detect dead connections quickly.
_DL_TIMEOUT = 30
_DL_RETRIES = 5
_DL_USER_AGENT = (
    f"logs-to-cookie/{__version__} (+https://github.com/zyblahblah/logs-to-cookie)"
)


def is_url(s: str) -> bool:
    return isinstance(s, str) and s.lower().startswith(("http://", "https://"))


def filename_from_url(url: str, fallback: str = "download.bin") -> str:
    parsed = urllib.parse.urlparse(url)
    name = Path(urllib.parse.unquote(parsed.path or "")).name
    return name or fallback


def _dl_open(url: str, headers: Optional[dict] = None, timeout: int = _DL_TIMEOUT):
    h = {"User-Agent": _DL_USER_AGENT}
    if headers:
        h.update(headers)
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=h), timeout=timeout
    )


def _dl_probe(url: str, timeout: int = 30) -> Tuple[Optional[int], bool, str]:
    try:
        req = urllib.request.Request(
            url, headers={"User-Agent": _DL_USER_AGENT}, method="HEAD"
        )
        with urllib.request.urlopen(req, timeout=timeout) as r:
            length = r.headers.get("Content-Length")
            ranges = (r.headers.get("Accept-Ranges") or "").lower() == "bytes"
            return (int(length) if length else None, ranges, r.geturl())
    except Exception:
        try:
            req = urllib.request.Request(
                url,
                headers={"User-Agent": _DL_USER_AGENT, "Range": "bytes=0-0"},
            )
            with urllib.request.urlopen(req, timeout=timeout) as r:
                cr = r.headers.get("Content-Range") or ""
                total = None
                if "/" in cr:
                    try:
                        total = int(cr.rsplit("/", 1)[1])
                    except ValueError:
                        total = None
                return (total, r.status == 206, r.geturl())
        except Exception:
            return (None, False, url)


def _dl_fmt_size(n: float) -> str:
    if n >= 1024 ** 3:
        return f"{n / 1024 ** 3:.2f} GB"
    if n >= 1024 ** 2:
        return f"{n / 1024 ** 2:.2f} MB"
    if n >= 1024:
        return f"{n / 1024:.2f} KB"
    return f"{int(n)} B"


def _dl_fmt_eta(seconds: float) -> str:
    s = max(0, int(seconds))
    if s < 60:
        return f"{s}s"
    m, s = divmod(s, 60)
    if m < 60:
        return f"{m}m{s:02d}s"
    h, m = divmod(m, 60)
    return f"{h}h{m:02d}m"


def _dl_bar(pct: float, width: int = 14) -> str:
    pct = max(0.0, min(100.0, pct))
    full = int(pct / 100 * width)
    rem = (pct / 100 * width) - full
    s = "■" * full
    if full < width:
        s += "▧" if rem >= 0.25 else "□"
        s += "□" * (width - full - 1)
    return s


def _dl_emit_status(stage: str, detail: str = "", stream=sys.stderr) -> None:
    block = f"🌀 Status: {stage}\n"
    if detail:
        block += f"📦 {detail}\n"
    stream.write(block)
    stream.flush()


class _Heartbeat:
    """Background heartbeat that re-emits a status block while a long
    synchronous step (e.g. extracting a multi-GB archive via ``7z``) is
    running. Keeps the bot's subprocess inactivity watchdog from
    firing on legitimately busy work that produces no output.
    """

    def __init__(
        self,
        stage: str,
        detail: str = "",
        *,
        interval: float = 30.0,
        stream=sys.stderr,
    ) -> None:
        self.stage = stage
        self.detail = detail
        self.interval = interval
        self.stream = stream
        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._start = 0.0

    def _emit(self) -> None:
        elapsed = time.monotonic() - self._start
        block = f"🌀 Status: {self.stage}\n"
        if self.detail:
            block += f"📦 {self.detail}\n"
        block += f"⏱️ Elapsed: {_dl_fmt_eta(elapsed)}\n"
        try:
            self.stream.write(block)
            self.stream.flush()
        except Exception:  # noqa: BLE001
            pass

    def _run(self) -> None:
        self._emit()
        while not self._stop.wait(self.interval):
            self._emit()

    def __enter__(self) -> "_Heartbeat":
        self._start = time.monotonic()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *exc) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2.0)


class _DLProgress:
    def __init__(self, label: str, stream=sys.stderr, interval: float = 1.0):
        self.label = label
        self.stream = stream
        self.interval = interval
        self.start = time.monotonic()
        self.last = 0.0
        self._lock = threading.Lock()
        self._isatty = bool(getattr(stream, "isatty", lambda: False)())
        # Lines emitted by the previous block; used to drive the ANSI
        # cursor-up redraw. Tracks the actual line count so the
        # unknown-total branch (5 lines) doesn't erase output above us
        # when redrawing.
        self._prev_lines = 0

    def __call__(self, done: int, total: int, elapsed: float) -> None:
        now = time.monotonic()
        with self._lock:
            done_final = bool(total) and done >= total
            if (
                now - self.last < self.interval
                and not done_final
                and self._prev_lines
            ):
                return
            self.last = now
            # Use our own monotonic origin instead of the caller's
            # per-attempt timer. ``_dl_stream_to`` resets its local
            # ``start`` on every retry but reports cumulative ``done``
            # (incl. ``bytes_done_offset``), which would otherwise
            # produce a wildly inflated speed and a too-rosy ETA right
            # after a resume.
            real_elapsed = max(now - self.start, 0.0)
            speed_mb = (done / real_elapsed / 1024 / 1024) if real_elapsed > 0 else 0.0
            if total:
                pct = 100.0 * done / total
                eta = (
                    ((total - done) / (done / real_elapsed))
                    if (done and real_elapsed > 0)
                    else 0.0
                )
                block = (
                    f"🌀 Status: Downloading...\n"
                    f"📦 {self.label}\n"
                    f"📊 [{_dl_bar(pct)}] {pct:.1f}%\n"
                    f"📡 Progress: {_dl_fmt_size(done)} / {_dl_fmt_size(total)}\n"
                    f"⚡ Speed: {speed_mb:.2f} MB/s | ETA: {_dl_fmt_eta(eta)}\n"
                    f"⏱️ Elapsed: {_dl_fmt_eta(real_elapsed)}\n"
                )
            else:
                block = (
                    f"🌀 Status: Downloading...\n"
                    f"📦 {self.label}\n"
                    f"📡 Progress: {_dl_fmt_size(done)}\n"
                    f"⚡ Speed: {speed_mb:.2f} MB/s\n"
                    f"⏱️ Elapsed: {_dl_fmt_eta(real_elapsed)}\n"
                )
            line_count = block.count("\n")
            if self._isatty and self._prev_lines:
                # Move up by the *previous* block's line count, not a
                # hard-coded constant.
                self.stream.write(f"\x1b[{self._prev_lines}A\x1b[J")
            self.stream.write(block)
            self.stream.flush()
            self._prev_lines = line_count


def _dl_stream_to(
    url: str,
    dest: Path,
    chunk: int,
    on_progress: Optional[Callable[[int, int, float], None]],
    total: Optional[int],
    *,
    headers: Optional[dict] = None,
    bytes_done_offset: int = 0,
    append: bool = False,
) -> None:
    written = 0
    start = time.monotonic()
    with _dl_open(url, headers=headers) as resp:
        if total is None:
            length = resp.headers.get("Content-Length")
            try:
                total = int(length) if length else None
            except ValueError:
                total = None
        mode = "ab" if append else "wb"
        with open(dest, mode) as f:
            while True:
                buf = resp.read(chunk)
                if not buf:
                    break
                f.write(buf)
                written += len(buf)
                if on_progress:
                    grand_total = (
                        ((total or 0) + bytes_done_offset)
                        if append
                        else (total or 0)
                    )
                    on_progress(
                        bytes_done_offset + written,
                        grand_total,
                        time.monotonic() - start,
                    )


def _dl_stream_with_resume(
    url: str,
    dest: Path,
    chunk: int,
    retries: int,
    on_progress: Optional[Callable[[int, int, float], None]],
    total: Optional[int],
) -> None:
    last_exc: Optional[Exception] = None
    for attempt in range(retries + 1):
        try:
            already = dest.stat().st_size if dest.exists() else 0
            if total is not None and already >= total > 0:
                return
            # Only resume via append when we can actually send a Range
            # request. Without ``total`` we have no way to skip bytes
            # server-side, so falling back to a full-file GET would
            # otherwise corrupt the output by appending on top of the
            # partial bytes.
            headers = (
                {"Range": f"bytes={already}-"} if already and total else None
            )
            if already and not headers:
                try:
                    dest.unlink()
                except FileNotFoundError:
                    pass
                already = 0
            _dl_stream_to(
                url,
                dest,
                chunk,
                on_progress,
                (total - already) if (total and headers) else total,
                headers=headers,
                bytes_done_offset=already,
                append=bool(headers),
            )
            return
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            if attempt >= retries:
                break
            backoff = min(2 ** attempt, 30)
            print(
                f"\n  single-stream attempt {attempt + 1} failed ({exc!r}); "
                f"resuming in {backoff}s…",
                file=sys.stderr,
                flush=True,
            )
            time.sleep(backoff)
    raise RuntimeError(f"single-stream download failed: {last_exc}")


def _dl_part(
    url: str,
    dest: Path,
    start: int,
    end: int,
    chunk: int,
    bump: Callable[[int], None],
    retries: int,
    timeout: int,
) -> None:
    written = 0
    last_exc: Optional[Exception] = None
    for attempt in range(retries + 1):
        try:
            req_start = start + written
            if req_start > end:
                return
            req = urllib.request.Request(
                url,
                headers={
                    "User-Agent": _DL_USER_AGENT,
                    "Range": f"bytes={req_start}-{end}",
                },
            )
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                # Server must return 206 (Partial Content). A 200
                # response means it's silently ignoring our Range
                # header and would dump the whole file at our part
                # offset — corrupting the result and making the
                # download appear suspiciously fast.
                status = getattr(resp, "status", None) or resp.getcode()
                if status != 206:
                    raise RuntimeError(
                        f"server ignored Range (HTTP {status}); "
                        f"part {start}-{end} cannot be safely written"
                    )
                with open(dest, "rb+") as f:
                    f.seek(req_start)
                    while True:
                        buf = resp.read(chunk)
                        if not buf:
                            break
                        # ``written`` is the cumulative bytes for this part
                        # across all attempts, so the remaining-bytes formula
                        # must be relative to ``start`` (not ``req_start``,
                        # which already includes the previously-written count
                        # at attempt entry).
                        remaining = end - start - written + 1
                        if len(buf) > remaining:
                            buf = buf[:remaining]
                        if not buf:
                            break
                        f.write(buf)
                        written += len(buf)
                        bump(len(buf))
            if (start + written - 1) >= end:
                return
            last_exc = RuntimeError(
                f"part {start}-{end}: ended early at {start + written - 1}"
            )
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
        if attempt >= retries:
            break
        time.sleep(min(2 ** attempt, 30))
    raise RuntimeError(f"part {start}-{end} failed: {last_exc}")


def stream_download(
    url: str,
    dest: Path,
    *,
    workers: int = 4,
    chunk: int = _DL_CHUNK,
    retries: int = _DL_RETRIES,
    timeout: int = _DL_TIMEOUT,
    label: str = "",
    show_progress: bool = True,
) -> Path:
    """Download ``url`` to ``dest`` (range-split parallel + single-stream resume fallback)."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    on_progress = _DLProgress(label or filename_from_url(url)) if show_progress else None
    total, ranges_ok, final_url = _dl_probe(url)
    use_url = final_url or url

    if not (total and ranges_ok and workers > 1 and total > chunk * 2):
        if show_progress:
            print(f"  single-stream: {use_url}", file=sys.stderr, flush=True)
        _dl_stream_with_resume(use_url, dest, chunk, retries, on_progress, total)
        _dl_check_final_size(dest, total)
        return dest

    with open(dest, "wb") as f:
        f.truncate(total)

    parts: List[Tuple[int, int]] = []
    part_size = max(chunk, (total + workers - 1) // workers)
    pos = 0
    while pos < total:
        end = min(pos + part_size, total) - 1
        parts.append((pos, end))
        pos = end + 1
    if show_progress:
        print(
            f"  range-split: {len(parts)} parts × {part_size / 1024 / 1024:.1f} MB → {use_url}",
            file=sys.stderr,
            flush=True,
        )

    bytes_done = [0]
    bd_lock = threading.Lock()
    start_t = time.monotonic()

    def bump(n: int) -> None:
        with bd_lock:
            bytes_done[0] += n
            if on_progress:
                on_progress(bytes_done[0], total, time.monotonic() - start_t)

    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as ex:
            futs = [
                ex.submit(
                    _dl_part, use_url, dest, s, e, chunk, bump, retries, timeout
                )
                for (s, e) in parts
            ]
            for fut in concurrent.futures.as_completed(futs):
                fut.result()
    except Exception as exc:  # noqa: BLE001
        if show_progress:
            print(
                f"\n  range-split failed ({exc!r}) → falling back to "
                "single stream with resume",
                file=sys.stderr,
                flush=True,
            )
        try:
            dest.unlink(missing_ok=True)
        except TypeError:
            if dest.exists():
                dest.unlink()
        _dl_stream_with_resume(use_url, dest, chunk, retries, on_progress, total)

    _dl_check_final_size(dest, total)
    return dest


def _dl_check_final_size(dest: Path, total: Optional[int]) -> None:
    """Raise if the on-disk file size doesn't match the advertised length."""
    if total is None:
        return
    actual = dest.stat().st_size
    if actual != total:
        raise RuntimeError(
            f"downloaded size mismatch: expected {total} bytes "
            f"({_dl_fmt_size(total)}), got {actual} bytes "
            f"({_dl_fmt_size(actual)}) — file is incomplete or corrupted; "
            "check the source URL is a direct download and not a "
            "redirect / preview page"
        )


def download_to_workdir(
    url: str,
    workdir: Path,
    *,
    workers: int = 4,
    label_prefix: str = "Downloading",
) -> Path:
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    name = filename_from_url(url)
    dest = workdir / name
    n = 1
    while dest.exists():
        dest = workdir / f"{Path(name).stem}_{n}{Path(name).suffix}"
        n += 1
    return stream_download(url, dest, workers=workers, label=name)


def _resolve_roots(
    stack: contextlib.ExitStack,
    input_path: str,
    passwords: List[str],
    *,
    workers: int = 4,
) -> Tuple[List[Path], List[Path]]:
    workdir: Optional[Path] = None
    if is_url(input_path):
        workdir = Path(
            stack.enter_context(tempfile.TemporaryDirectory(prefix="l2c-dl-"))
        )
        inp = download_to_workdir(input_path, workdir, workers=workers)
    else:
        inp = Path(input_path)
        if not inp.exists():
            return [], []
    do_extract = bool(passwords) or (inp.is_file() and is_archive(inp))
    if not do_extract:
        return [inp], []
    if workdir is None:
        workdir = Path(
            stack.enter_context(tempfile.TemporaryDirectory(prefix="l2c-"))
        )
    inputs: List[Path] = []
    if inp.is_file():
        inputs.append(inp)
    else:
        inputs.append(inp)
        for child in inp.rglob("*"):
            if child.is_file() and is_archive(child):
                inputs.append(child)
    with _Heartbeat("Extracting archive...", inp.name):
        return expand_input(inputs, passwords, workdir)


def _report_failures(failures: List[Path]) -> None:
    if not failures:
        return
    print(
        f"warning: {len(failures)} archive(s) could not be extracted "
        f"(wrong password or missing tool):",
        file=sys.stderr,
    )
    for f in failures[:10]:
        print(f"  - {f}", file=sys.stderr)
    if len(failures) > 10:
        print(f"  ... and {len(failures) - 10} more", file=sys.stderr)


def cmd_ulp(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(
            stack, args.input, args.password, workers=getattr(args, "workers", 4)
        )
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        filters = [
            f.strip().lower() for f in (args.filter or "").split(",") if f.strip()
        ]
        out, owned = _open_out(args.output)
        seen = set()
        count = 0
        try:
            for root in roots:
                for url, user, pwd, _ in collect_credentials(root):
                    if filters:
                        hay = (url + " " + domain_of(url)).lower()
                        if not any(flt in hay for flt in filters):
                            continue
                    line = f"{url}:{user}:{pwd}"
                    if not args.no_dedupe:
                        if line in seen:
                            continue
                        seen.add(line)
                    out.write(line + "\n")
                    count += 1
        finally:
            if owned:
                out.close()
        print(f"wrote {count} ULP entries to {args.output}", file=sys.stderr)
        return 0


def _write_cookies_file(path: Path, cookies: List[Dict], fmt: str) -> None:
    if path.parent and str(path.parent) not in ("", "."):
        path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "netscape":
        with open(path, "w", encoding="utf-8") as f:
            f.write(NETSCAPE_HEADER)
            for c in cookies:
                f.write(to_netscape_line(c) + "\n")
    else:
        path.write_text(json.dumps(cookies, indent=2), encoding="utf-8")


def cmd_cookies(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(
            stack, args.input, args.password, workers=getattr(args, "workers", 4)
        )
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        filters = [
            f.strip().lower() for f in (args.filter or "").split(",") if f.strip()
        ]
        per_source = getattr(args, "per_source", False)

        if per_source:
            out_dir = Path(args.output)
            out_dir.mkdir(parents=True, exist_ok=True)
            filename = "cookies.txt" if args.format == "netscape" else "cookies.json"

            groups: Dict[str, List[Dict]] = {}
            for root in roots:
                for cookie, src_path in collect_cookies_with_source(root):
                    domain = (cookie.get("domain") or "").lower()
                    if filters and not any(flt in domain for flt in filters):
                        continue
                    name = safe_source_name(source_name_for(src_path, root))
                    groups.setdefault(name, []).append(cookie)

            total = 0
            for name in sorted(groups):
                deduped = dedupe_cookies(groups[name])
                if not deduped:
                    continue
                _write_cookies_file(out_dir / name / filename, deduped, args.format)
                total += len(deduped)
                print(
                    f"  {name}: {len(deduped)} cookies -> {out_dir / name / filename}",
                    file=sys.stderr,
                )
            print(
                f"wrote {total} cookies across {len(groups)} source(s) to {out_dir}",
                file=sys.stderr,
            )
            return 0

        cookies: List[Dict] = []
        for root in roots:
            for cookie in collect_cookies(root):
                domain = (cookie.get("domain") or "").lower()
                if filters and not any(flt in domain for flt in filters):
                    continue
                cookies.append(cookie)
        cookies = dedupe_cookies(cookies)

        out_path = Path(args.output)
        _write_cookies_file(out_path, cookies, args.format)
        print(f"wrote {len(cookies)} cookies to {out_path}", file=sys.stderr)
        return 0


def _sort_per_source(
    roots: List[Path], out_dir: Path, keywords: List[str]
) -> Dict[str, int]:
    """Per-victim folder, one Netscape file per source cookie file::

        out_dir/<victim>/<orig_name>_<hash6>.txt   # one Netscape file per source
        out_dir/<victim>/creds.txt                 # merged keyword-matching creds
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    kws_lower = [k.lower() for k in keywords]

    by_file: Dict[Tuple[str, Path], List[Dict]] = {}
    by_file_root: Dict[Tuple[str, Path], Path] = {}
    for r in roots:
        for cookie, src_path in collect_cookies_with_source(r):
            domain = (cookie.get("domain") or "").lower()
            if not domain:
                continue
            if not any(k in domain for k in kws_lower):
                continue
            victim = safe_source_name(source_name_for(src_path, r))
            key = (victim, src_path)
            by_file.setdefault(key, []).append(cookie)
            by_file_root.setdefault(key, r)

    cookie_files_written = 0
    cookies_total = 0
    for (victim, src_path), cookies in by_file.items():
        deduped = dedupe_cookies(cookies)
        if not deduped:
            continue
        r = by_file_root[(victim, src_path)]
        try:
            rel = src_path.resolve().relative_to(r.resolve())
            hash_input = str(rel)
        except ValueError:
            hash_input = str(src_path)
        h = hashlib.sha1(hash_input.encode("utf-8")).hexdigest()[:6]
        fname = safe_source_name(f"{src_path.name}_{h}") + ".txt"
        target_dir = out_dir / victim
        target_dir.mkdir(parents=True, exist_ok=True)
        with open(target_dir / fname, "w", encoding="utf-8") as f:
            f.write(NETSCAPE_HEADER)
            for c in deduped:
                f.write(to_netscape_line(c) + "\n")
        cookie_files_written += 1
        cookies_total += len(deduped)

    ulp_buf: Dict[str, List[str]] = {}
    seen_ulp: Dict[str, set] = {}
    for r in roots:
        for url, user, pwd, src_path in collect_credentials(r):
            host = domain_of(url)
            haystack = (url + " " + host).lower()
            if not any(k in haystack for k in kws_lower):
                continue
            victim = safe_source_name(source_name_for(src_path, r))
            line = f"{url}:{user}:{pwd}"
            s = seen_ulp.setdefault(victim, set())
            if line in s:
                continue
            s.add(line)
            ulp_buf.setdefault(victim, []).append(line)

    for victim, lines in ulp_buf.items():
        d = out_dir / victim
        d.mkdir(parents=True, exist_ok=True)
        (d / "creds.txt").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )

    victims = set(ulp_buf) | {v for v, _ in by_file}
    return {
        "victims": len(victims),
        "ulp": sum(len(v) for v in ulp_buf.values()),
        "cookie_files": cookie_files_written,
        "cookies": cookies_total,
    }


def cmd_sort(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(
            stack, args.input, args.password, workers=getattr(args, "workers", 4)
        )
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        keywords = [k.strip() for k in args.keywords.split(",") if k.strip()]
        if not keywords:
            print("provide --keywords", file=sys.stderr)
            return 2

        per_source = getattr(args, "per_source", False)
        if per_source:
            s = _sort_per_source(roots, Path(args.output), keywords)
            print(
                f"  {s['victims']} hit(s), {s['ulp']} ulp, "
                f"{s['cookie_files']} cookie file(s) "
                f"({s['cookies']} cookies)",
                file=sys.stderr,
            )
            return 0

        with _Heartbeat("Sorting logs...", ", ".join(keywords)):
            stats = sort_logs(roots, Path(args.output), keywords)
        for k, (u, c) in stats.items():
            print(f"  {k}: {u} ulp, {c} cookies", file=sys.stderr)
        return 0


def _add_password_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--password",
        action="append",
        default=[],
        help=(
            "Password for archived logs (.zip/.rar/.7z). May be repeated to "
            "try several. Without --password, archives in the input are left "
            "untouched."
        ),
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help=(
            "Parallel range-split download workers when input is an HTTP(S) "
            "URL. Default 4. Set to 1 to force a single stream."
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="logs_to_cookie.py",
        description="Sort and convert log dumps into ULP and cookie formats (single-file edition).",
    )
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="cmd", required=True)

    pu = sub.add_parser("ulp", help="extract URL:USER:PASS lines from log dumps")
    pu.add_argument("input", help="path to log directory or file")
    pu.add_argument("-o", "--output", default="-", help="output file (- for stdout)")
    pu.add_argument(
        "--filter",
        help="comma-separated keywords matched against URL/host (substring)",
    )
    pu.add_argument(
        "--no-dedupe", action="store_true", help="keep duplicate lines (default: dedupe)"
    )
    _add_password_arg(pu)
    pu.set_defaults(func=cmd_ulp)

    pc = sub.add_parser("cookies", help="collect and normalize cookies")
    pc.add_argument("input", help="path to log directory or file")
    pc.add_argument(
        "-o",
        "--output",
        required=True,
        help=(
            "output file path (default), or output directory when "
            "--per-source is set"
        ),
    )
    pc.add_argument(
        "--format",
        choices=["netscape", "json"],
        default="netscape",
        help="output format (default: netscape cookies.txt)",
    )
    pc.add_argument(
        "--filter",
        help="comma-separated keywords matched against cookie domain (substring)",
    )
    pc.add_argument(
        "--per-source",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "write one folder per source (victim) under --output, each "
            "containing a single cookies.txt/.json for that source. "
            "Default is on; pass --no-per-source for a single merged file."
        ),
    )
    _add_password_arg(pc)
    pc.set_defaults(func=cmd_cookies)

    ps = sub.add_parser(
        "sort",
        help="bucket logs into per-keyword ULP + cookies files",
    )
    ps.add_argument("input", help="path to log directory")
    ps.add_argument("-o", "--output", required=True, help="output directory")
    ps.add_argument(
        "--keywords",
        required=True,
        help="comma-separated keywords (e.g. netflix,spotify,roblox)",
    )
    ps.add_argument(
        "--per-source",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "write one folder per victim with a hit "
            "(<output>/<victim>/cookies.txt + creds.txt) — keywords act "
            "as a filter, not as folders. Default is on; pass "
            "--no-per-source for the legacy merged <keyword>.ulp.txt + "
            "<keyword>.cookies.txt layout."
        ),
    )
    _add_password_arg(ps)
    ps.set_defaults(func=cmd_sort)

    return p


# ---------------------------------------------------------------------------
# Interactive menu (used when no subcommand is supplied)
# ---------------------------------------------------------------------------


def _ask(prompt: str, default: Optional[str] = None) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default or ""
    if not answer and default is not None:
        return default
    return answer


def _ask_workers(inp: str) -> int:
    if not is_url(inp):
        return 4
    raw = _ask(
        "Parallel download workers for URL (1 = single stream)", default="4"
    )
    try:
        return max(1, int(raw))
    except ValueError:
        return 4


def _ask_passwords() -> List[str]:
    raw = _ask(
        "Archive password(s), comma-separated (leave blank if none)", default=""
    )
    if not raw:
        return []
    return [p.strip() for p in raw.split(",") if p.strip()]


def _ask_nonempty(prompt: str, default: Optional[str] = None) -> str:
    while True:
        val = _ask(prompt, default=default)
        if val:
            return val
        print("  (required)")


def _build_args(**kwargs) -> argparse.Namespace:
    ns = argparse.Namespace()
    for k, v in kwargs.items():
        setattr(ns, k, v)
    return ns


def run_interactive() -> int:
    """Simple menu-driven flow used when the script is run with no args.

    Designed for Termux / mobile "run this file" launchers where you don't
    have a persistent shell to pass CLI flags.
    """
    print("=" * 52)
    print(f" logs-to-cookie v{__version__} — interactive mode")
    print("=" * 52)
    print(" 1) ulp      — extract URL:USER:PASS")
    print(" 2) cookies  — build cookies.txt / JSON")
    print(" 3) sort     — bucket by keyword (ULP + cookies per keyword)")
    print(" q) quit")
    print()

    try:
        choice = _ask("Choose [1/2/3/q]", default="3").lower()
    except KeyboardInterrupt:
        print()
        return 0

    if choice in ("q", "quit", "exit"):
        return 0

    try:
        if choice in ("1", "ulp"):
            inp = _ask_nonempty("Input path or http(s) URL (dir, file, .zip/.rar/.7z)")
            passwords = _ask_passwords()
            workers = _ask_workers(inp)
            filt = _ask("Filter keywords (substring, comma-separated; blank=all)", default="")
            out = _ask("Output file (- for stdout)", default="creds.ulp.txt")
            return cmd_ulp(
                _build_args(
                    input=inp,
                    output=out,
                    filter=filt or None,
                    no_dedupe=False,
                    password=passwords,
                    workers=workers,
                )
            )

        if choice in ("2", "cookies"):
            inp = _ask_nonempty("Input path or http(s) URL (dir, file, .zip/.rar/.7z)")
            passwords = _ask_passwords()
            workers = _ask_workers(inp)
            filt = _ask(
                "Filter keywords (cookie domain substring; blank=all)", default=""
            )
            fmt_choice = _ask("Format [1=netscape, 2=json]", default="1")
            fmt = "json" if fmt_choice.strip() in ("2", "json") else "netscape"
            per_src_ans = _ask(
                "One folder per source/victim? [Y/n]", default="y"
            ).lower()
            per_source = per_src_ans not in ("n", "no", "0", "false")
            if per_source:
                out = _ask("Output directory", default="cookies_out")
            else:
                default_out = "cookies.txt" if fmt == "netscape" else "cookies.json"
                out = _ask("Output file", default=default_out)
            return cmd_cookies(
                _build_args(
                    input=inp,
                    output=out,
                    format=fmt,
                    filter=filt or None,
                    per_source=per_source,
                    password=passwords,
                    workers=workers,
                )
            )

        if choice in ("3", "sort"):
            inp = _ask_nonempty("Input path or http(s) URL (dir, file, .zip/.rar/.7z)")
            passwords = _ask_passwords()
            workers = _ask_workers(inp)
            keywords = _ask_nonempty(
                "Keywords to sort by (comma-separated, e.g. netflix,spotify,roblox)"
            )
            per_src_ans = _ask(
                "One folder per victim with a hit (victim/cookies.txt)? [Y/n]",
                default="y",
            ).lower()
            per_source = per_src_ans not in ("n", "no", "0", "false")
            out = _ask("Output directory", default="sorted")
            return cmd_sort(
                _build_args(
                    input=inp,
                    output=out,
                    keywords=keywords,
                    per_source=per_source,
                    password=passwords,
                    workers=workers,
                )
            )
    except KeyboardInterrupt:
        print("\naborted")
        return 130

    print(f"unknown choice: {choice!r}")
    return 2


def main(argv=None) -> int:
    # Drop into the interactive menu when no arguments were given (e.g. when
    # the script is run by a mobile launcher that just double-taps the file).
    if argv is None:
        argv = sys.argv[1:]
    if not argv:
        return run_interactive()

    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
