#!/usr/bin/env python3
"""logs-to-cookie (single-file edition).

Sort and convert stealer-style log dumps into ULP and cookie formats.

No install needed — just::

    python logs_to_cookie.py --help
    python logs_to_cookie.py ulp     /path/to/logs -o creds.txt
    python logs_to_cookie.py cookies /path/to/logs -o cookies.txt
    python logs_to_cookie.py sort    /path/to/logs --keywords netflix,spotify -o sorted/

Stdlib only, Python 3.9+.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Tuple
from urllib.parse import urlparse

__version__ = "0.5.0"

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

PASSWORD_NAME_HINTS = (
    "password",
    "passwords",
    "all passwords",
    "all_passwords",
    "passwordsall",
    "logins",
    "credentials",
)

URL_RE = re.compile(
    r"^(?:URL|HOST(?:NAME)?|SITE|SOFT\s*URL|ORIGIN|URL\s*\(form\)|URL\s*Origin)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
USER_RE = re.compile(
    r"^(?:USER(?:NAME)?|LOGIN|EMAIL|USER\s*ID|USER\s*NAME)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
PASS_RE = re.compile(
    r"^(?:PASS(?:WORD)?|PWD)\s*[:=]\s*(.+)$",
    re.IGNORECASE,
)
INLINE_ULP_RE = re.compile(
    r"^(?P<url>(?:https?|android)://[^/:\s]+(?::\d+)?(?:/[^\s:]*)?):"
    r"(?P<user>[^:\s]+):"
    r"(?P<pwd>.+)$"
)

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by logs-to-cookie. Do not edit.\n\n"
)


def domain_of(url: str) -> str:
    try:
        host = urlparse(url).hostname or ""
    except ValueError:
        host = ""
    return host.lower()


# ---------------------------------------------------------------------------
# Credentials parsing
# ---------------------------------------------------------------------------


def _emit(cur: dict) -> Iterator[Tuple[str, str, str]]:
    if cur.get("url") and cur.get("user") is not None and cur.get("pwd") is not None:
        yield cur["url"], cur["user"], cur["pwd"]


def parse_credentials_text(text: str) -> Iterator[Tuple[str, str, str]]:
    """Yield ``(url, user, pwd)`` triples parsed from a credential dump."""
    cur: dict = {"url": None, "user": None, "pwd": None}

    for raw in text.splitlines():
        line = raw.strip().lstrip("\ufeff")
        if not line:
            yield from _emit(cur)
            cur = {"url": None, "user": None, "pwd": None}
            continue

        m = INLINE_ULP_RE.match(line)
        if m:
            yield m.group("url"), m.group("user"), m.group("pwd")
            cur = {"url": None, "user": None, "pwd": None}
            continue

        m = URL_RE.match(line)
        if m:
            yield from _emit(cur)
            cur = {"url": m.group(1).strip(), "user": None, "pwd": None}
            continue
        m = USER_RE.match(line)
        if m:
            cur["user"] = m.group(1).strip()
            continue
        m = PASS_RE.match(line)
        if m:
            cur["pwd"] = m.group(1).strip()
            if cur["url"] and cur["user"] is not None:
                yield cur["url"], cur["user"], cur["pwd"]
                cur = {"url": None, "user": None, "pwd": None}
            continue

    yield from _emit(cur)


def is_password_file(path: Path) -> bool:
    name = path.name.lower()
    if not name.endswith((".txt", ".log")):
        return False
    return any(hint in name for hint in PASSWORD_NAME_HINTS)


def iter_password_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        if is_password_file(root):
            yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and is_password_file(path):
            yield path


def collect_credentials(root: Path) -> Iterator[Tuple[str, str, str, Path]]:
    for path in iter_password_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for url, user, pwd in parse_credentials_text(text):
            yield url, user, pwd, path


# ---------------------------------------------------------------------------
# Cookie parsing / serialization
# ---------------------------------------------------------------------------


def parse_netscape(text: str) -> Iterator[Dict]:
    for raw in text.splitlines():
        if not raw.strip():
            continue
        line = raw
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
        elif line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, flag, path, secure, expires, name, value = parts
        try:
            exp_int = int(float(expires))
        except (TypeError, ValueError):
            exp_int = 0
        yield {
            "domain": domain,
            "hostOnly": flag.strip().upper() != "TRUE",
            "path": path or "/",
            "secure": secure.strip().upper() == "TRUE",
            "expires": exp_int,
            "name": name,
            "value": value,
        }


def parse_json_cookies(text: str) -> Iterator[Dict]:
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if isinstance(data, dict):
        if isinstance(data.get("cookies"), list):
            data = data["cookies"]
        else:
            data = [data]
    if not isinstance(data, list):
        return
    for entry in data:
        if not isinstance(entry, dict):
            continue
        domain = entry.get("domain") or entry.get("Domain") or entry.get("host") or ""
        if not domain:
            continue
        host_only = entry.get("hostOnly")
        if host_only is None:
            host_only = not str(domain).startswith(".")
        expires_raw = (
            entry.get("expirationDate")
            or entry.get("expires")
            or entry.get("Expires")
            or 0
        )
        try:
            expires = int(float(expires_raw))
        except (TypeError, ValueError):
            expires = 0
        yield {
            "domain": str(domain),
            "hostOnly": bool(host_only),
            "path": entry.get("path") or "/",
            "secure": bool(entry.get("secure", False)),
            "expires": expires,
            "name": entry.get("name", ""),
            "value": entry.get("value", ""),
        }


def to_netscape_line(cookie: Dict) -> str:
    domain = cookie.get("domain", "") or ""
    host_only = bool(cookie.get("hostOnly"))
    if host_only:
        if domain.startswith("."):
            domain = domain[1:]
        flag = "FALSE"
    else:
        if domain and not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
    return "\t".join(
        [
            domain,
            flag,
            cookie.get("path") or "/",
            "TRUE" if cookie.get("secure") else "FALSE",
            str(int(cookie.get("expires") or 0)),
            cookie.get("name", "") or "",
            cookie.get("value", "") or "",
        ]
    )


def _looks_like_cookie_path(path: Path) -> bool:
    name = path.name.lower()
    if name.endswith((".txt", ".json")) and "cookie" in name:
        return True
    parents = {p.name.lower() for p in path.parents}
    if "cookies" in parents and path.suffix.lower() in {".txt", ".json", ""}:
        return True
    return False


def iter_cookie_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        if _looks_like_cookie_path(root):
            yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and _looks_like_cookie_path(path):
            yield path


def collect_cookies(root: Path) -> Iterator[Dict]:
    for cookie, _src in collect_cookies_with_source(root):
        yield cookie


def collect_cookies_with_source(root: Path) -> Iterator[Tuple[Dict, Path]]:
    """Like :func:`collect_cookies` but also yields the originating file."""
    for path in iter_cookie_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.strip():
            continue
        stripped = text.lstrip()
        if path.suffix.lower() == ".json" or stripped.startswith(("[", "{")):
            yielded = False
            for cookie in parse_json_cookies(text):
                yielded = True
                yield cookie, path
            if yielded:
                continue
        for cookie in parse_netscape(text):
            yield cookie, path


_ARCHIVE_TEMPDIR_RE = re.compile(r"^x\d{3}_")


def source_name_for(path: Path, root: Path) -> str:
    """Derive a human-friendly source (victim) name for ``path`` under ``root``."""
    try:
        rel = path.resolve().relative_to(root.resolve())
    except ValueError:
        name = path.parent.name or "unknown"
        return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"

    parts = rel.parts
    if parts and parts[0].lower() in ("cookies", "cookie"):
        name = root.name or "unknown"
    elif parts:
        name = parts[0]
    else:
        name = root.name or "unknown"
    return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"


def safe_source_name(name: str) -> str:
    cleaned = "".join(
        c if c.isalnum() or c in "-_." else "_" for c in (name or "").strip()
    )
    return cleaned or "unknown"


def dedupe_cookies(cookies: Iterable[Dict]) -> List[Dict]:
    seen = set()
    out: List[Dict] = []
    for c in cookies:
        key = (c.get("domain", ""), c.get("path", ""), c.get("name", ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(c)
    return out


# ---------------------------------------------------------------------------
# Archive extraction (password-protected logs)
# ---------------------------------------------------------------------------

ARCHIVE_EXTS = {".zip", ".rar", ".7z"}


def is_archive(path: Path) -> bool:
    return path.suffix.lower() in ARCHIVE_EXTS


def _have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def _seven_zip_binary() -> Optional[str]:
    for cand in ("7z", "7za", "7zz"):
        if _have(cand):
            return cand
    return None


def _try_zip(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    try:
        zf = zipfile.ZipFile(archive)
    except (zipfile.BadZipFile, OSError):
        return False
    try:
        for pwd in passwords:
            pwd_b = pwd.encode("utf-8") if pwd else None
            try:
                zf.extractall(dest, pwd=pwd_b)
                return True
            except RuntimeError:
                continue
            except zipfile.BadZipFile:
                return False
    finally:
        zf.close()
    return False


def _try_7z(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    binary = _seven_zip_binary()
    if not binary:
        return False
    for pwd in passwords:
        cmd = [binary, "x", "-y", f"-o{dest}"]
        cmd.append(f"-p{pwd}" if pwd is not None else "-p")
        cmd.append(str(archive))
        try:
            result = subprocess.run(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=600,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0:
            return True
    return False


def _try_unrar(archive: Path, dest: Path, passwords: List[Optional[str]]) -> bool:
    if not _have("unrar"):
        return False
    for pwd in passwords:
        cmd = ["unrar", "x", "-y", "-inul"]
        cmd.append(f"-p{pwd}" if pwd is not None else "-p-")
        cmd.append(str(archive))
        cmd.append(str(dest) + os.sep)
        try:
            result = subprocess.run(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=600,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0:
            return True
    return False


def extract_archive(
    archive: Path, dest: Path, passwords: List[Optional[str]]
) -> bool:
    dest.mkdir(parents=True, exist_ok=True)
    ext = archive.suffix.lower()
    if ext == ".zip":
        if _try_zip(archive, dest, passwords):
            return True
        return _try_7z(archive, dest, passwords)
    if ext == ".rar":
        if _try_unrar(archive, dest, passwords):
            return True
        return _try_7z(archive, dest, passwords)
    if ext == ".7z":
        return _try_7z(archive, dest, passwords)
    return False


def expand_input(
    inputs: Iterable[Path],
    passwords: Iterable[str],
    workdir: Path,
    recurse: bool = True,
) -> Tuple[List[Path], List[Path]]:
    pwd_list: List[Optional[str]] = [None]
    for p in passwords:
        if p and p not in pwd_list:
            pwd_list.append(p)
    workdir.mkdir(parents=True, exist_ok=True)

    roots: List[Path] = []
    failures: List[Path] = []
    queue: List[Path] = []
    seen: set = set()

    for inp in inputs:
        inp = inp.resolve()
        if inp.is_file() and is_archive(inp):
            queue.append(inp)
        else:
            roots.append(inp)

    counter = 0
    while queue:
        archive = queue.pop()
        if archive in seen:
            continue
        seen.add(archive)
        counter += 1
        safe = "".join(c if c.isalnum() or c in "-_." else "_" for c in archive.stem)
        target = workdir / f"x{counter:03d}_{safe or 'arch'}"
        if extract_archive(archive, target, pwd_list):
            roots.append(target)
            if recurse:
                for nested in target.rglob("*"):
                    if nested.is_file() and is_archive(nested) and nested not in seen:
                        queue.append(nested)
        else:
            failures.append(archive)

    return roots, failures


# ---------------------------------------------------------------------------
# Sorter
# ---------------------------------------------------------------------------


def _safe_keyword(k: str) -> str:
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in k.strip()) or "kw"


def sort_logs(
    root, out_dir: Path, keywords: Iterable[str]
) -> Dict[str, Tuple[int, int]]:
    if isinstance(root, Path):
        roots = [root]
    else:
        roots = list(root)
    kws = [k.strip() for k in keywords if k and k.strip()]
    if not kws:
        return {}
    out_dir.mkdir(parents=True, exist_ok=True)

    ulp_handles: Dict[str, "object"] = {}
    cookie_handles: Dict[str, "object"] = {}
    seen_ulp = {k: set() for k in kws}
    seen_cookie = {k: set() for k in kws}
    counts = {k: [0, 0] for k in kws}

    try:
        for k in kws:
            slug = _safe_keyword(k)
            ulp_handles[k] = open(out_dir / f"{slug}.ulp.txt", "w", encoding="utf-8")
            cookie_handles[k] = open(
                out_dir / f"{slug}.cookies.txt", "w", encoding="utf-8"
            )
            cookie_handles[k].write(NETSCAPE_HEADER)

        for r in roots:
            for url, user, pwd, _ in collect_credentials(r):
                host = domain_of(url)
                haystack = (url + " " + host).lower()
                line = f"{url}:{user}:{pwd}"
                for k in kws:
                    if k.lower() in haystack:
                        if line in seen_ulp[k]:
                            continue
                        seen_ulp[k].add(line)
                        ulp_handles[k].write(line + "\n")
                        counts[k][0] += 1

        for r in roots:
            for cookie in collect_cookies(r):
                domain = (cookie.get("domain") or "").lower()
                if not domain:
                    continue
                line = to_netscape_line(cookie)
                for k in kws:
                    if k.lower() in domain:
                        if line in seen_cookie[k]:
                            continue
                        seen_cookie[k].add(line)
                        cookie_handles[k].write(line + "\n")
                        counts[k][1] += 1
    finally:
        for f in ulp_handles.values():
            f.close()
        for f in cookie_handles.values():
            f.close()

    return {k: (counts[k][0], counts[k][1]) for k in kws}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _open_out(path: str):
    if path == "-":
        return sys.stdout, False
    p = Path(path)
    if p.parent and str(p.parent) not in ("", "."):
        p.parent.mkdir(parents=True, exist_ok=True)
    return open(p, "w", encoding="utf-8"), True


def _resolve_roots(
    stack: contextlib.ExitStack,
    input_path: str,
    passwords: List[str],
) -> Tuple[List[Path], List[Path]]:
    inp = Path(input_path)
    if not inp.exists():
        return [], []
    do_extract = bool(passwords) or (inp.is_file() and is_archive(inp))
    if not do_extract:
        return [inp], []
    workdir = Path(stack.enter_context(tempfile.TemporaryDirectory(prefix="l2c-")))
    inputs: List[Path] = []
    if inp.is_file():
        inputs.append(inp)
    else:
        inputs.append(inp)
        for child in inp.rglob("*"):
            if child.is_file() and is_archive(child):
                inputs.append(child)
    return expand_input(inputs, passwords, workdir)


def _report_failures(failures: List[Path]) -> None:
    if not failures:
        return
    print(
        f"warning: {len(failures)} archive(s) could not be extracted "
        f"(wrong password or missing tool):",
        file=sys.stderr,
    )
    for f in failures[:10]:
        print(f"  - {f}", file=sys.stderr)
    if len(failures) > 10:
        print(f"  ... and {len(failures) - 10} more", file=sys.stderr)


def cmd_ulp(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(stack, args.input, args.password)
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        filters = [
            f.strip().lower() for f in (args.filter or "").split(",") if f.strip()
        ]
        out, owned = _open_out(args.output)
        seen = set()
        count = 0
        try:
            for root in roots:
                for url, user, pwd, _ in collect_credentials(root):
                    if filters:
                        hay = (url + " " + domain_of(url)).lower()
                        if not any(flt in hay for flt in filters):
                            continue
                    line = f"{url}:{user}:{pwd}"
                    if not args.no_dedupe:
                        if line in seen:
                            continue
                        seen.add(line)
                    out.write(line + "\n")
                    count += 1
        finally:
            if owned:
                out.close()
        print(f"wrote {count} ULP entries to {args.output}", file=sys.stderr)
        return 0


def _write_cookies_file(path: Path, cookies: List[Dict], fmt: str) -> None:
    if path.parent and str(path.parent) not in ("", "."):
        path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "netscape":
        with open(path, "w", encoding="utf-8") as f:
            f.write(NETSCAPE_HEADER)
            for c in cookies:
                f.write(to_netscape_line(c) + "\n")
    else:
        path.write_text(json.dumps(cookies, indent=2), encoding="utf-8")


def cmd_cookies(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(stack, args.input, args.password)
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        filters = [
            f.strip().lower() for f in (args.filter or "").split(",") if f.strip()
        ]
        per_source = getattr(args, "per_source", False)

        if per_source:
            out_dir = Path(args.output)
            out_dir.mkdir(parents=True, exist_ok=True)
            filename = "cookies.txt" if args.format == "netscape" else "cookies.json"

            groups: Dict[str, List[Dict]] = {}
            for root in roots:
                for cookie, src_path in collect_cookies_with_source(root):
                    domain = (cookie.get("domain") or "").lower()
                    if filters and not any(flt in domain for flt in filters):
                        continue
                    name = safe_source_name(source_name_for(src_path, root))
                    groups.setdefault(name, []).append(cookie)

            total = 0
            for name in sorted(groups):
                deduped = dedupe_cookies(groups[name])
                if not deduped:
                    continue
                _write_cookies_file(out_dir / name / filename, deduped, args.format)
                total += len(deduped)
                print(
                    f"  {name}: {len(deduped)} cookies -> {out_dir / name / filename}",
                    file=sys.stderr,
                )
            print(
                f"wrote {total} cookies across {len(groups)} source(s) to {out_dir}",
                file=sys.stderr,
            )
            return 0

        cookies: List[Dict] = []
        for root in roots:
            for cookie in collect_cookies(root):
                domain = (cookie.get("domain") or "").lower()
                if filters and not any(flt in domain for flt in filters):
                    continue
                cookies.append(cookie)
        cookies = dedupe_cookies(cookies)

        out_path = Path(args.output)
        _write_cookies_file(out_path, cookies, args.format)
        print(f"wrote {len(cookies)} cookies to {out_path}", file=sys.stderr)
        return 0


def _sort_per_source(
    roots: List[Path], out_dir: Path, keywords: List[str]
) -> Dict[str, Dict]:
    """Per-keyword, per-victim layout::

        out_dir/<keyword>/<victim>/cookies.txt + creds.txt
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    stats: Dict[str, Dict] = {
        k: {"victims": set(), "ulp": 0, "cookies": 0} for k in keywords
    }
    ulp_buf: Dict = {}
    seen_ulp: Dict = {}
    cookie_buf: Dict = {}
    seen_cookie: Dict = {}

    for r in roots:
        for url, user, pwd, src_path in collect_credentials(r):
            host = domain_of(url)
            haystack = (url + " " + host).lower()
            src = safe_source_name(source_name_for(src_path, r))
            line = f"{url}:{user}:{pwd}"
            for k in keywords:
                if k.lower() in haystack:
                    key = (k, src)
                    seen = seen_ulp.setdefault(key, set())
                    if line in seen:
                        continue
                    seen.add(line)
                    ulp_buf.setdefault(key, []).append(line)
                    stats[k]["ulp"] += 1
                    stats[k]["victims"].add(src)

    for r in roots:
        for cookie, src_path in collect_cookies_with_source(r):
            domain = (cookie.get("domain") or "").lower()
            if not domain:
                continue
            src = safe_source_name(source_name_for(src_path, r))
            line = to_netscape_line(cookie)
            for k in keywords:
                if k.lower() in domain:
                    key = (k, src)
                    seen = seen_cookie.setdefault(key, set())
                    if line in seen:
                        continue
                    seen.add(line)
                    cookie_buf.setdefault(key, []).append(line)
                    stats[k]["cookies"] += 1
                    stats[k]["victims"].add(src)

    for (k, src), lines in ulp_buf.items():
        if not lines:
            continue
        path = out_dir / _safe_keyword(k) / src / "creds.txt"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for (k, src), lines in cookie_buf.items():
        if not lines:
            continue
        path = out_dir / _safe_keyword(k) / src / "cookies.txt"
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(NETSCAPE_HEADER)
            for ln in lines:
                f.write(ln + "\n")

    return stats


def cmd_sort(args: argparse.Namespace) -> int:
    with contextlib.ExitStack() as stack:
        roots, failures = _resolve_roots(stack, args.input, args.password)
        if not roots and not failures:
            print(f"input not found: {args.input}", file=sys.stderr)
            return 2
        _report_failures(failures)
        keywords = [k.strip() for k in args.keywords.split(",") if k.strip()]
        if not keywords:
            print("provide --keywords", file=sys.stderr)
            return 2

        per_source = getattr(args, "per_source", False)
        if per_source:
            stats = _sort_per_source(roots, Path(args.output), keywords)
            for k, s in stats.items():
                print(
                    f"  {k}: {len(s['victims'])} hit(s), {s['ulp']} ulp, "
                    f"{s['cookies']} cookies",
                    file=sys.stderr,
                )
            return 0

        stats = sort_logs(roots, Path(args.output), keywords)
        for k, (u, c) in stats.items():
            print(f"  {k}: {u} ulp, {c} cookies", file=sys.stderr)
        return 0


def _add_password_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--password",
        action="append",
        default=[],
        help=(
            "Password for archived logs (.zip/.rar/.7z). May be repeated to "
            "try several. Without --password, archives in the input are left "
            "untouched."
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="logs_to_cookie.py",
        description="Sort and convert log dumps into ULP and cookie formats (single-file edition).",
    )
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="cmd", required=True)

    pu = sub.add_parser("ulp", help="extract URL:USER:PASS lines from log dumps")
    pu.add_argument("input", help="path to log directory or file")
    pu.add_argument("-o", "--output", default="-", help="output file (- for stdout)")
    pu.add_argument(
        "--filter",
        help="comma-separated keywords matched against URL/host (substring)",
    )
    pu.add_argument(
        "--no-dedupe", action="store_true", help="keep duplicate lines (default: dedupe)"
    )
    _add_password_arg(pu)
    pu.set_defaults(func=cmd_ulp)

    pc = sub.add_parser("cookies", help="collect and normalize cookies")
    pc.add_argument("input", help="path to log directory or file")
    pc.add_argument(
        "-o",
        "--output",
        required=True,
        help=(
            "output file path (default), or output directory when "
            "--per-source is set"
        ),
    )
    pc.add_argument(
        "--format",
        choices=["netscape", "json"],
        default="netscape",
        help="output format (default: netscape cookies.txt)",
    )
    pc.add_argument(
        "--filter",
        help="comma-separated keywords matched against cookie domain (substring)",
    )
    pc.add_argument(
        "--per-source",
        action="store_true",
        help=(
            "write one folder per source (victim) under --output, each "
            "containing a single cookies.txt/.json for that source"
        ),
    )
    _add_password_arg(pc)
    pc.set_defaults(func=cmd_cookies)

    ps = sub.add_parser(
        "sort",
        help="bucket logs into per-keyword ULP + cookies files",
    )
    ps.add_argument("input", help="path to log directory")
    ps.add_argument("-o", "--output", required=True, help="output directory")
    ps.add_argument(
        "--keywords",
        required=True,
        help="comma-separated keywords (e.g. netflix,spotify,roblox)",
    )
    ps.add_argument(
        "--per-source",
        action="store_true",
        help=(
            "instead of one ulp.txt + cookies.txt per keyword, write one "
            "folder per (keyword, victim) hit: "
            "<output>/<keyword>/<victim>/cookies.txt + creds.txt"
        ),
    )
    _add_password_arg(ps)
    ps.set_defaults(func=cmd_sort)

    return p


# ---------------------------------------------------------------------------
# Interactive menu (used when no subcommand is supplied)
# ---------------------------------------------------------------------------


def _ask(prompt: str, default: Optional[str] = None) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default or ""
    if not answer and default is not None:
        return default
    return answer


def _ask_passwords() -> List[str]:
    raw = _ask(
        "Archive password(s), comma-separated (leave blank if none)", default=""
    )
    if not raw:
        return []
    return [p.strip() for p in raw.split(",") if p.strip()]


def _ask_nonempty(prompt: str, default: Optional[str] = None) -> str:
    while True:
        val = _ask(prompt, default=default)
        if val:
            return val
        print("  (required)")


def _build_args(**kwargs) -> argparse.Namespace:
    ns = argparse.Namespace()
    for k, v in kwargs.items():
        setattr(ns, k, v)
    return ns


def run_interactive() -> int:
    """Simple menu-driven flow used when the script is run with no args.

    Designed for Termux / mobile "run this file" launchers where you don't
    have a persistent shell to pass CLI flags.
    """
    print("=" * 52)
    print(f" logs-to-cookie v{__version__} — interactive mode")
    print("=" * 52)
    print(" 1) ulp      — extract URL:USER:PASS")
    print(" 2) cookies  — build cookies.txt / JSON")
    print(" 3) sort     — bucket by keyword (ULP + cookies per keyword)")
    print(" q) quit")
    print()

    try:
        choice = _ask("Choose [1/2/3/q]", default="3").lower()
    except KeyboardInterrupt:
        print()
        return 0

    if choice in ("q", "quit", "exit"):
        return 0

    try:
        if choice in ("1", "ulp"):
            inp = _ask_nonempty("Input path (dir, file, or .zip/.rar/.7z)")
            passwords = _ask_passwords()
            filt = _ask("Filter keywords (substring, comma-separated; blank=all)", default="")
            out = _ask("Output file (- for stdout)", default="creds.ulp.txt")
            return cmd_ulp(
                _build_args(
                    input=inp,
                    output=out,
                    filter=filt or None,
                    no_dedupe=False,
                    password=passwords,
                )
            )

        if choice in ("2", "cookies"):
            inp = _ask_nonempty("Input path (dir, file, or .zip/.rar/.7z)")
            passwords = _ask_passwords()
            filt = _ask(
                "Filter keywords (cookie domain substring; blank=all)", default=""
            )
            fmt_choice = _ask("Format [1=netscape, 2=json]", default="1")
            fmt = "json" if fmt_choice.strip() in ("2", "json") else "netscape"
            per_src_ans = _ask(
                "One folder per source/victim? [y/N]", default="n"
            ).lower()
            per_source = per_src_ans in ("y", "yes", "1", "true")
            if per_source:
                out = _ask("Output directory", default="cookies_out")
            else:
                default_out = "cookies.txt" if fmt == "netscape" else "cookies.json"
                out = _ask("Output file", default=default_out)
            return cmd_cookies(
                _build_args(
                    input=inp,
                    output=out,
                    format=fmt,
                    filter=filt or None,
                    per_source=per_source,
                    password=passwords,
                )
            )

        if choice in ("3", "sort"):
            inp = _ask_nonempty("Input path (dir, file, or .zip/.rar/.7z)")
            passwords = _ask_passwords()
            keywords = _ask_nonempty(
                "Keywords to sort by (comma-separated, e.g. netflix,spotify,roblox)"
            )
            per_src_ans = _ask(
                "One folder per hit (keyword/victim/cookies.txt)? [Y/n]",
                default="y",
            ).lower()
            per_source = per_src_ans not in ("n", "no", "0", "false")
            out = _ask("Output directory", default="sorted")
            return cmd_sort(
                _build_args(
                    input=inp,
                    output=out,
                    keywords=keywords,
                    per_source=per_source,
                    password=passwords,
                )
            )
    except KeyboardInterrupt:
        print("\naborted")
        return 130

    print(f"unknown choice: {choice!r}")
    return 2


def main(argv=None) -> int:
    # Drop into the interactive menu when no arguments were given (e.g. when
    # the script is run by a mobile launcher that just double-taps the file).
    if argv is None:
        argv = sys.argv[1:]
    if not argv:
        return run_interactive()

    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
