"""Streaming log → Netscape cookie pipeline.

The processor reads a remote URL chunk-by-chunk (no full disk download
needed for plain text logs), splits it into lines, applies an optional
keyword filter, and converts every matching line into a single-entry
Netscape cookie file: ``cookie_1.txt``, ``cookie_2.txt``, …

For password-protected archives (.zip / .rar / .7z) the URL is first
streamed to a temp file, extracted with the provided password, then
the same line-by-line pipeline runs over every text file inside.
"""

from __future__ import annotations

import re
import shutil
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Iterator, List, Optional

import requests

from extract import ARCHIVE_SUFFIXES, extract_archive, is_archive

CHUNK_SIZE = 64 * 1024
USER_AGENT = "logs-to-cookie/1.0 (+https://github.com/zyblahblah/logs-to-cookie)"

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by logs-to-cookie. Do not edit.\n"
    "\n"
)


ProgressCallback = Callable[[str], None]


@dataclass
class ProcessResult:
    """Outcome of a :func:`process_url` run."""

    output_dir: Path
    zip_path: Path
    item_count: int
    bytes_read: int


# ---------------------------------------------------------------------------
# Streaming helpers
# ---------------------------------------------------------------------------


def _filename_from_url(url: str) -> str:
    name = Path(url.split("?", 1)[0]).name
    return name or "download.bin"


def _looks_like_archive_url(url: str) -> bool:
    name = _filename_from_url(url).lower()
    return any(name.endswith(suf) for suf in ARCHIVE_SUFFIXES)


def stream_lines(
    url: str,
    *,
    chunk_size: int = CHUNK_SIZE,
    on_bytes: Optional[Callable[[int], None]] = None,
) -> Iterator[str]:
    """Yield decoded lines from ``url`` as they arrive.

    Buffers a single trailing partial line between chunks so a line
    split across chunk boundaries is never duplicated or truncated.
    Decoding is permissive (errors=replace) because logs commonly
    contain mixed encodings and we don't want one bad byte to kill
    the whole stream.
    """
    headers = {"User-Agent": USER_AGENT}
    with requests.get(url, stream=True, headers=headers, timeout=60) as resp:
        resp.raise_for_status()
        buf = ""
        for chunk in resp.iter_content(chunk_size=chunk_size):
            if not chunk:
                continue
            if on_bytes is not None:
                on_bytes(len(chunk))
            buf += chunk.decode("utf-8", errors="replace")
            while True:
                nl = buf.find("\n")
                if nl < 0:
                    break
                line, buf = buf[:nl], buf[nl + 1 :]
                yield line.rstrip("\r")
        if buf:
            yield buf.rstrip("\r")


def stream_to_file(
    url: str,
    dest: Path,
    *,
    chunk_size: int = CHUNK_SIZE,
    on_bytes: Optional[Callable[[int], None]] = None,
) -> Path:
    """Stream ``url`` to ``dest`` chunk-by-chunk."""
    headers = {"User-Agent": USER_AGENT}
    dest.parent.mkdir(parents=True, exist_ok=True)
    with requests.get(url, stream=True, headers=headers, timeout=60) as resp:
        resp.raise_for_status()
        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=chunk_size):
                if not chunk:
                    continue
                if on_bytes is not None:
                    on_bytes(len(chunk))
                f.write(chunk)
    return dest


# ---------------------------------------------------------------------------
# Netscape parser
# ---------------------------------------------------------------------------


_NETSCAPE_RE = re.compile(
    r"^(?P<domain>[^\s#][^\t]*)\t"
    r"(?P<flag>TRUE|FALSE)\t"
    r"(?P<path>[^\t]*)\t"
    r"(?P<secure>TRUE|FALSE)\t"
    r"(?P<expires>-?\d+)\t"
    r"(?P<name>[^\t]*)\t"
    r"(?P<value>.*)$"
)


def parse_netscape_line(line: str) -> Optional[dict]:
    """Try to interpret ``line`` as a Netscape-formatted cookie row.

    Many stealer logs already emit Netscape format. Comments
    (``#``-prefixed) and blank lines return ``None``. Returns a dict
    with the named fields when the line matches; otherwise ``None``.
    """
    s = line.strip()
    if not s or s.startswith("#"):
        return None
    m = _NETSCAPE_RE.match(s)
    if not m:
        return None
    return m.groupdict()


def to_netscape_line(cookie: dict) -> str:
    """Render a parsed cookie back into a single Netscape-formatted line."""
    return (
        f"{cookie['domain']}\t{cookie['flag']}\t{cookie['path']}\t"
        f"{cookie['secure']}\t{cookie['expires']}\t"
        f"{cookie['name']}\t{cookie['value']}"
    )


def matches_filter(line: str, keyword: Optional[str]) -> bool:
    """Case-insensitive substring match used as the user filter."""
    if not keyword:
        return True
    return keyword.lower() in line.lower()


# ---------------------------------------------------------------------------
# Per-item file writer
# ---------------------------------------------------------------------------


def write_cookie_file(
    out_dir: Path, index: int, cookie: dict
) -> Path:
    """Write ``cookie`` as ``cookie_<index>.txt`` in Netscape format."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"cookie_{index}.txt"
    body = NETSCAPE_HEADER + to_netscape_line(cookie) + "\n"
    path.write_text(body, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------


def process_lines(
    lines: Iterable[str],
    out_dir: Path,
    keyword: Optional[str],
) -> int:
    """Walk ``lines``, write a cookie file per matched Netscape entry.

    Returns the number of cookie files written.
    """
    count = 0
    for line in lines:
        if not matches_filter(line, keyword):
            continue
        cookie = parse_netscape_line(line)
        if cookie is None:
            continue
        count += 1
        write_cookie_file(out_dir, count, cookie)
    return count


def _walk_text_files(root: Path) -> Iterator[Path]:
    for p in root.rglob("*"):
        if p.is_file():
            yield p


def _read_text_lines(path: Path) -> Iterator[str]:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                yield line.rstrip("\r\n")
    except OSError:
        return


def process_url(
    url: str,
    workdir: Path,
    *,
    keyword: Optional[str] = None,
    password: Optional[str] = None,
    on_status: Optional[ProgressCallback] = None,
) -> ProcessResult:
    """Run the full pipeline for ``url`` and return the zipped result.

    * Plain text URL → :func:`stream_lines` straight into
      :func:`process_lines`.
    * Archive URL (``.zip``/``.rar``/``.7z``) or non-empty
      ``password`` → stream to disk, extract with ``password``, walk
      every file inside line-by-line.

    ``workdir`` must already exist; intermediate downloads and the
    extracted tree are placed under it. The final zip is written to
    ``workdir / "cookies_result.zip"``.
    """
    workdir = Path(workdir)
    out_dir = workdir / "output"
    out_dir.mkdir(parents=True, exist_ok=True)

    bytes_read = [0]

    def _bump(n: int) -> None:
        bytes_read[0] += n

    is_arch = _looks_like_archive_url(url) or bool(password)

    if not is_arch:
        if on_status:
            on_status(f"Streaming {_filename_from_url(url)} (text mode)...")
        lines = stream_lines(url, on_bytes=_bump)
        item_count = process_lines(lines, out_dir, keyword)
    else:
        archive_path = workdir / _filename_from_url(url)
        if on_status:
            on_status(f"Downloading archive {archive_path.name}...")
        stream_to_file(url, archive_path, on_bytes=_bump)

        if on_status:
            on_status(f"Extracting {archive_path.name}...")
        extract_dir = workdir / "extracted"
        extract_dir.mkdir(parents=True, exist_ok=True)
        passwords: List[Optional[str]] = [None]
        if password:
            passwords.append(password)
        ok = extract_archive(archive_path, extract_dir, passwords)
        if not ok:
            raise RuntimeError(
                f"could not extract {archive_path.name} — wrong password "
                "or missing 7z/unrar binary for AES/RAR archives"
            )

        if on_status:
            on_status("Scanning extracted files...")
        item_count = 0
        for f in _walk_text_files(extract_dir):
            for line in _read_text_lines(f):
                if not matches_filter(line, keyword):
                    continue
                cookie = parse_netscape_line(line)
                if cookie is None:
                    continue
                item_count += 1
                write_cookie_file(out_dir, item_count, cookie)

    if on_status:
        on_status(f"Packaging {item_count} cookie file(s)...")
    zip_path = workdir / "cookies_result.zip"
    _zip_dir(out_dir, zip_path)

    return ProcessResult(
        output_dir=out_dir,
        zip_path=zip_path,
        item_count=item_count,
        bytes_read=bytes_read[0],
    )


def _zip_dir(src: Path, dest: Path) -> None:
    """Zip every file under ``src`` into ``dest`` (DEFLATE level 1)."""
    with zipfile.ZipFile(
        dest, "w", zipfile.ZIP_DEFLATED, compresslevel=1
    ) as zf:
        for p in sorted(src.rglob("*")):
            if p.is_file():
                zf.write(p, p.relative_to(src))


__all__ = [
    "ProcessResult",
    "process_url",
    "process_lines",
    "stream_lines",
    "stream_to_file",
    "parse_netscape_line",
    "to_netscape_line",
    "matches_filter",
    "write_cookie_file",
    "NETSCAPE_HEADER",
]
