"""Collect and normalize cookies from stealer logs.

Supports two on-disk formats commonly found in logs:

* Netscape ``cookies.txt`` files (7 tab-separated columns).
* JSON arrays exported by browser extensions (EditThisCookie, Cookie-Editor).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, Iterable, Iterator, List

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by logs-to-cookie. Do not edit.\n\n"
)


def parse_netscape(text: str) -> Iterator[Dict]:
    for raw in text.splitlines():
        if not raw.strip():
            continue
        # Some dumps prefix lines with "#HttpOnly_" — strip it before the
        # generic comment check.
        line = raw
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
        elif line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, flag, path, secure, expires, name, value = parts
        try:
            exp_int = int(float(expires))
        except (TypeError, ValueError):
            exp_int = 0
        yield {
            "domain": domain,
            "hostOnly": flag.strip().upper() != "TRUE",
            "path": path or "/",
            "secure": secure.strip().upper() == "TRUE",
            "expires": exp_int,
            "name": name,
            "value": value,
        }


def parse_json_cookies(text: str) -> Iterator[Dict]:
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if isinstance(data, dict):
        if isinstance(data.get("cookies"), list):
            data = data["cookies"]
        else:
            data = [data]
    if not isinstance(data, list):
        return
    for entry in data:
        if not isinstance(entry, dict):
            continue
        domain = entry.get("domain") or entry.get("Domain") or entry.get("host") or ""
        if not domain:
            continue
        host_only = entry.get("hostOnly")
        if host_only is None:
            host_only = not str(domain).startswith(".")
        expires_raw = (
            entry.get("expirationDate")
            or entry.get("expires")
            or entry.get("Expires")
            or 0
        )
        try:
            expires = int(float(expires_raw))
        except (TypeError, ValueError):
            expires = 0
        yield {
            "domain": str(domain),
            "hostOnly": bool(host_only),
            "path": entry.get("path") or "/",
            "secure": bool(entry.get("secure", False)),
            "expires": expires,
            "name": entry.get("name", ""),
            "value": entry.get("value", ""),
        }


def to_netscape_line(cookie: Dict) -> str:
    domain = cookie.get("domain", "") or ""
    host_only = bool(cookie.get("hostOnly"))
    if host_only:
        if domain.startswith("."):
            domain = domain[1:]
        flag = "FALSE"
    else:
        if domain and not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
    return "\t".join(
        [
            domain,
            flag,
            cookie.get("path") or "/",
            "TRUE" if cookie.get("secure") else "FALSE",
            str(int(cookie.get("expires") or 0)),
            cookie.get("name", "") or "",
            cookie.get("value", "") or "",
        ]
    )


def _looks_like_cookie_path(path: Path) -> bool:
    name = path.name.lower()
    if name.endswith((".txt", ".json")) and "cookie" in name:
        return True
    # Stealer logs often place cookie txt files under a folder named "Cookies".
    parents = {p.name.lower() for p in path.parents}
    if "cookies" in parents and path.suffix.lower() in {".txt", ".json", ""}:
        return True
    return False


def iter_cookie_files(root: Path) -> Iterator[Path]:
    """Walk directory tree efficiently without timeout limits."""
    if root.is_file():
        if _looks_like_cookie_path(root):
            yield root
        return
    
    # Use os.walk for faster traversal than rglob
    for dirpath, dirnames, filenames in os.walk(str(root)):
        # Skip hidden directories to speed up scanning
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]
        
        for filename in filenames:
            filepath = Path(dirpath) / filename
            if _looks_like_cookie_path(filepath):
                yield filepath


def collect_cookies(root: Path) -> Iterator[Dict]:
    for path in iter_cookie_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.strip():
            continue
        # Try JSON first when it looks like JSON.
        stripped = text.lstrip()
        if path.suffix.lower() == ".json" or stripped.startswith(("[", "{")):
            yielded = False
            for cookie in parse_json_cookies(text):
                yielded = True
                yield cookie
            if yielded:
                continue
        # Fall back to Netscape format.
        yield from parse_netscape(text)


def dedupe(cookies: Iterable[Dict]) -> List[Dict]:
    seen = set()
    out: List[Dict] = []
    for c in cookies:
        key = (c.get("domain", ""), c.get("path", ""), c.get("name", ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(c)
    return out
