"""Collect and normalize cookies from stealer logs.

Supports two on-disk formats commonly found in logs:

* Netscape ``cookies.txt`` files (7 tab-separated columns).
* JSON arrays exported by browser extensions (EditThisCookie, Cookie-Editor).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Tuple

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by logs-to-cookie. Do not edit.\n\n"
)


def parse_netscape(text: str) -> Iterator[Dict]:
    for raw in text.splitlines():
        if not raw.strip():
            continue
        # Some dumps prefix lines with "#HttpOnly_" — strip it before the
        # generic comment check.
        line = raw
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_") :]
        elif line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, flag, path, secure, expires, name, value = parts
        try:
            exp_int = int(float(expires))
        except (TypeError, ValueError):
            exp_int = 0
        yield {
            "domain": domain,
            "hostOnly": flag.strip().upper() != "TRUE",
            "path": path or "/",
            "secure": secure.strip().upper() == "TRUE",
            "expires": exp_int,
            "name": name,
            "value": value,
        }


def parse_json_cookies(text: str) -> Iterator[Dict]:
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if isinstance(data, dict):
        if isinstance(data.get("cookies"), list):
            data = data["cookies"]
        else:
            data = [data]
    if not isinstance(data, list):
        return
    for entry in data:
        if not isinstance(entry, dict):
            continue
        domain = entry.get("domain") or entry.get("Domain") or entry.get("host") or ""
        if not domain:
            continue
        host_only = entry.get("hostOnly")
        if host_only is None:
            host_only = not str(domain).startswith(".")
        expires_raw = (
            entry.get("expirationDate")
            or entry.get("expires")
            or entry.get("Expires")
            or 0
        )
        try:
            expires = int(float(expires_raw))
        except (TypeError, ValueError):
            expires = 0
        yield {
            "domain": str(domain),
            "hostOnly": bool(host_only),
            "path": entry.get("path") or "/",
            "secure": bool(entry.get("secure", False)),
            "expires": expires,
            "name": entry.get("name", ""),
            "value": entry.get("value", ""),
        }


def to_netscape_line(cookie: Dict) -> str:
    domain = cookie.get("domain", "") or ""
    host_only = bool(cookie.get("hostOnly"))
    if host_only:
        if domain.startswith("."):
            domain = domain[1:]
        flag = "FALSE"
    else:
        if domain and not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
    return "\t".join(
        [
            domain,
            flag,
            cookie.get("path") or "/",
            "TRUE" if cookie.get("secure") else "FALSE",
            str(int(cookie.get("expires") or 0)),
            cookie.get("name", "") or "",
            cookie.get("value", "") or "",
        ]
    )


def _looks_like_cookie_path(path: Path) -> bool:
    name = path.name.lower()
    if name.endswith((".txt", ".json")) and "cookie" in name:
        return True
    # Stealer logs often place cookie txt files under a folder named "Cookies".
    parents = {p.name.lower() for p in path.parents}
    if "cookies" in parents and path.suffix.lower() in {".txt", ".json", ""}:
        return True
    return False


def iter_cookie_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        if _looks_like_cookie_path(root):
            yield root
        return
    for path in root.rglob("*"):
        if path.is_file() and _looks_like_cookie_path(path):
            yield path


def collect_cookies(root: Path) -> Iterator[Dict]:
    for cookie, _src in collect_cookies_with_source(root):
        yield cookie


def collect_cookies_with_source(root: Path) -> Iterator[Tuple[Dict, Path]]:
    """Yield ``(cookie, source_file)`` tuples — same as :func:`collect_cookies`
    but also exposes the originating file so callers can group by victim.
    """
    for path in iter_cookie_files(root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.strip():
            continue
        stripped = text.lstrip()
        if path.suffix.lower() == ".json" or stripped.startswith(("[", "{")):
            yielded = False
            for cookie in parse_json_cookies(text):
                yielded = True
                yield cookie, path
            if yielded:
                continue
        for cookie in parse_netscape(text):
            yield cookie, path


_ARCHIVE_TEMPDIR_RE = re.compile(r"^x\d{3}_")


def source_name_for(path: Path, root: Path) -> str:
    """Derive a human-friendly ``source`` (usually victim) name for ``path``.

    - ``root/victim01/Cookies/foo.txt`` -> ``"victim01"``
    - ``root/Cookies/foo.txt`` -> root's name.
    - Strips the ``xNNN_`` prefix the extraction helper adds to temp dirs.
    """
    try:
        rel = path.resolve().relative_to(root.resolve())
    except ValueError:
        name = path.parent.name or "unknown"
        return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"

    parts = rel.parts
    if parts and parts[0].lower() in ("cookies", "cookie"):
        name = root.name or "unknown"
    elif parts:
        name = parts[0]
    else:
        name = root.name or "unknown"
    return _ARCHIVE_TEMPDIR_RE.sub("", name) or "unknown"


def safe_source_name(name: str) -> str:
    cleaned = "".join(
        c if c.isalnum() or c in "-_." else "_" for c in (name or "").strip()
    )
    return cleaned or "unknown"


def dedupe(cookies: Iterable[Dict]) -> List[Dict]:
    seen = set()
    out: List[Dict] = []
    for c in cookies:
        key = (c.get("domain", ""), c.get("path", ""), c.get("name", ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(c)
    return out
